In [1]:
#importing things
import pandas as pd
import os
import numpy as np
import csv
import pylab as pl
import matplotlib.pyplot as plt
import copy
import scipy
import scipy.stats as stats
from scipy.stats import linregress
from scipy.stats import t
from scipy.stats import chi2
from scipy.stats import sem
from tqdm.notebook import tqdm
import scipy.stats as st
from scipy.linalg import hadamard
from scipy.stats import ttest_ind_from_stats
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression
from mpl_toolkits.mplot3d import Axes3D
from scipy.stats import ttest_ind_from_stats
from sklearn.manifold import TSNE
from scipy.stats import pearsonr
from collections import OrderedDict
import seaborn as sns
from functools import reduce
from scipy.optimize import curve_fit
from operator import itemgetter
import math

def lighten_color(color, amount=0.5):  
    # --------------------- SOURCE: @IanHincks ---------------------
    try:
        c = mc.cnames[color]
    except:
        c = color
    c = colorsys.rgb_to_hls(*mc.to_rgb(c))
    return colorsys.hls_to_rgb(c[0], 1 - amount * (1 - c[1]), c[2])

In [2]:
#define categories based on mutation position
def find_pos_1(variant):
    pos = [mut for mut in variant]
    if pos[0] == "1":
        return 1
    else:
        return 0
def find_pos_2(variant):
    pos = [mut for mut in variant]
    if pos[1] == "1":
        return 1
    else:
        return 0
def find_pos_3(variant):
    pos = [mut for mut in variant]
    if pos[2] == "1":
        return 1
    else:
        return 0
def find_pos_4(variant):
    pos = [mut for mut in variant]
    if pos[3] == "1":
        return 1
    else:
        return 0
def find_pos_5(variant):
    pos = [mut for mut in variant]
    if pos[4] == "1":
        return 1
    else:
        return 0
def find_pos_6(variant):
    pos = [mut for mut in variant]
    if pos[5] == "1":
        return 1
    else:
        return 0
def find_pos_7(variant):
    pos = [mut for mut in variant]
    if pos[6] == "1":
        return 1
    else:
        return 0
def find_pos_8(variant):
    pos = [mut for mut in variant]
    if pos[7] == "1":
        return 1
    else:
        return 0
def find_pos_9(variant):
    pos = [mut for mut in variant]
    if pos[8] == "1":
        return 1
    else:
        return 0
def find_pos_10(variant):
    pos = [mut for mut in variant]
    if pos[9 ] == "1":
        return 1
    else:
        return 0
def find_pos_11(variant):
    pos = [mut for mut in variant]
    if pos[10] == "1":
        return 1
    else:
        return 0
def find_pos_12(variant):
    pos = [mut for mut in variant]
    if pos[11] == "1":
        return 1
    else:
        return 0
def find_pos_13(variant):
    pos = [mut for mut in variant]
    if pos[12] == "1":
        return 1
    else:
        return 0
def find_pos_14(variant):
    pos = [mut for mut in variant]
    if pos[13] == "1":
        return 1
    else:
        return 0
def find_pos_15(variant):
    pos = [mut for mut in variant]
    if pos[14] == "1":
        return 1
    else:
        return 0
def find_pos_16(variant):
    pos = [mut for mut in variant]
    if pos[15] == "1":
        return 1
    else:
        return 0
    
#add a column with the number of mutations and save the file
def sum_digits(digit):
    return sum(int(x) for x in digit if x.isdigit())

## MI15

In [3]:
L = 16
mutation_names = ['N26D','S29R','Y35N','Y48C','D49Y','V98I','G31D','Y33H','M34I','H35N','N52H','G57D','L83V','S84N','R85G','R87K']

df = pd.read_csv('20220723_fracbound_v2.csv',
                 dtype={"geno":"str"})
df["variant_int"] = df.geno.apply(lambda x: int(x, 2))

df = df.set_index("variant_int").reindex(range(0, 2**L)).reset_index()
sequences_int = range(0,2**L)
print(sequences_int)
for ii in range(L):
    df[f"mutation_{ii+1}"] = df.geno.str[ii] == '1'


dft = df.set_index("geno")
dfpl = pd.DataFrame()
exp = dft.MI_frac_mean.to_dict()
errexp = dft.MI_frac_sem.to_dict()
nbmuts, deltas, muts, keeps, deltas_err, sources, targets = [], [], [], [], [], [], []
for im, m in tqdm(enumerate(mutation_names)):
    muts += [m]*(len(df))
    for s in df.geno:
        deltas += [exp[s[:im] + '1' + s[im+1:]] - exp[s]]
        deltas_err += [np.sqrt(errexp[s]**2 + errexp[s[:im] + '1' + s[im+1:]]**2)]
        nbmuts += [s.count('1')]
        keeps += [s[im] != '1']
        sources += [s]
        targets += [s[:im] + '1' + s[im+1:]]
dfpl = pd.DataFrame()
dfpl["Mutation"] = muts
dfpl[r'dfrac'] = deltas
dfpl[r'Number of mutations'] = nbmuts
dfpl[r'dfrac_sem'] = deltas_err
dfpl[r'source'] = sources
dfpl[r'target'] = targets
dfpl = dfpl[keeps]

range(0, 65536)

0it [00:00, ?it/s]

In [4]:
dfpl['pos1'] = dfpl['source'].apply(find_pos_1)
dfpl['pos2'] = dfpl['source'].apply(find_pos_2)
dfpl['pos3'] = dfpl['source'].apply(find_pos_3)
dfpl['pos4'] = dfpl['source'].apply(find_pos_4)
dfpl['pos5'] = dfpl['source'].apply(find_pos_5)
dfpl['pos6'] = dfpl['source'].apply(find_pos_6)
dfpl['pos7'] = dfpl['source'].apply(find_pos_7)
dfpl['pos8'] = dfpl['source'].apply(find_pos_8)
dfpl['pos9'] = dfpl['source'].apply(find_pos_9)
dfpl['pos10'] = dfpl['source'].apply(find_pos_10)
dfpl['pos11'] = dfpl['source'].apply(find_pos_11)
dfpl['pos12'] = dfpl['source'].apply(find_pos_12)
dfpl['pos13'] = dfpl['source'].apply(find_pos_13)
dfpl['pos14'] = dfpl['source'].apply(find_pos_14)
dfpl['pos15'] = dfpl['source'].apply(find_pos_15)
dfpl['pos16'] = dfpl['source'].apply(find_pos_16)
d=dfpl.rename(columns={'Number of mutations':'N'})
dfpl.to_csv('20220723_CH65_dfrac_MI_v2.csv', index=False)

In [5]:
dfpl

,Mutation,dfrac,Number of mutations,dfrac_sem,source,target,pos1,pos2,pos3,pos4,...,pos7,pos8,pos9,pos10,pos11,pos12,pos13,pos14,pos15,pos16
0,N26D,-0.008936,0,0.003311,0000000000000000,1000000000000000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,N26D,0.002399,1,0.007674,0000000000000001,1000000000000001,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,N26D,-0.000223,1,0.005571,0000000000000010,1000000000000010,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,N26D,-0.008997,2,0.005523,0000000000000011,1000000000000011,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
4,N26D,-0.004773,1,0.004182,0000000000000100,1000000000000100,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048566,R87K,0.017905,14,0.010503,1111111111110110,1111111111110111,1,1,1,1,...,1,1,1,1,1,1,0,1,1,0
1048568,R87K,0.017015,13,0.013395,1111111111111000,1111111111111001,1,1,1,1,...,1,1,1,1,1,1,1,0,0,0
1048570,R87K,0.013297,14,0.015129,1111111111111010,1111111111111011,1,1,1,1,...,1,1,1,1,1,1,1,0,1,0
1048572,R87K,0.002127,14,0.009496,1111111111111100,1111111111111101,1,1,1,1,...,1,1,1,1,1,1,1,1,0,0
1048574,R87K,0.010583,15,0.014475,1111111111111110,1111111111111111,1,1,1,1,...,1,1,1,1,1,1,1,1,1,0